apiVersion: apps/v1
kind: Deployment
metadata:
  name: contosoair
  labels:
    app: contosoair
    kubernetes.azure.com/generator: devhub
  namespace: contosoair
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contosoair
  template:
    metadata:
      labels:
        app: contosoair
    spec:
      containers:
        - name: contosoair
          image: acrworkflow1724788006402.azurecr.io/contosoair:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
